namename: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install buildozer cython==0.29.33
          sudo apt-get install -y scons libncurses5 libstdc++6 zlib1g-dev libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good

      - name: Build with Buildozer
        run: |
          yes | buildozer init
          # تنظیمات نام برنامه
          sed -i 's/^title = .*/title = AmirKabir RP/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = amirkabirrp/' buildozer.spec
          # اضافه کردن فرمت عکس به فایل تنظیمات
          sed -i 's/^source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          # شروع پخت APK
          buildozer android debug
